import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { NgSelectModule } from '@ng-select/ng-select';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HomeComponent } from './pages/home/home.component';
import { AutoGeneratedFormComponent } from './shared/auto-generated-form/auto-generated-form.component';
import { AutoGeneratedFormSectionComponent } from './shared/auto-generated-form/auto-generated-form-section/auto-generated-form-section.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { DateMaxValidatorDirective } from './shared/directives/validators/date-max-validator.directive';
import { DateMinValidatorDirective } from './shared/directives/validators/date-min-validator.directive';
import { StringCheckValidatorDirective } from './shared/directives/validators/string-check-validator.directive';
import { StringMaxLengthValidatorDirective } from './shared/directives/validators/string-max-length-validator.directive';
import { StringMinLengthValidatorDirective } from './shared/directives/validators/string-min-length-validator.directive';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    AutoGeneratedFormComponent,
    AutoGeneratedFormSectionComponent,
    StringCheckValidatorDirective,
    DateMinValidatorDirective,
    DateMaxValidatorDirective,
    StringMinLengthValidatorDirective,
    StringMaxLengthValidatorDirective,
  ],
  imports: [BrowserModule, AppRoutingModule, FormsModule, ReactiveFormsModule, NgSelectModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
