import { Component } from '@angular/core';
import { AutoGeneratedFormComponent } from './shared/auto-generated-form/auto-generated-form.component';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'renderingPOC';
}