import { ComponentFixture, TestBed } from '@angular/core/testing';

import { AutoGeneratedFormSectionComponent } from './auto-generated-form-section.component';

describe('AutoGeneratedFormSectionComponent', () => {
  let component: AutoGeneratedFormSectionComponent;
  let fixture: ComponentFixture<AutoGeneratedFormSectionComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [ AutoGeneratedFormSectionComponent ]
    })
    .compileComponents();

    fixture = TestBed.createComponent(AutoGeneratedFormSectionComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
